.TH make-ssl-cert 8
.SH NAME
make-ssl-cert - Debconf wrapper for openssl
.SH SYNOPSIS
.B make-ssl-cert
[\fI\,OPTION\/\fR]... \fItemplate\fR
\fIoutput-certificate\fR
.br
.B make-ssl-cert [\fI\,OPTION\/\fR]... generate-default-snakeoil
.br
.SH "DESCRIPTION"
make-ssl-cert is a simple debconf to openssl wrapper to create self-signed
certificates.
It requires a source template (Ex: /usr/share/ssl-cert/ssleay.cnf)
and it will place the new generated certificate in the specified
output file.
.br
Invoked with "generate-default-snakeoil", it will generate
/etc/ssl/certs/ssl-cert-snakeoil.pem and /etc/ssl/private/ssl-cert-snakeoil.key.
.SH OPTIONS
A summary of options are included below.
.TP
.B \-\-force\-overwrite
Always create a new certificate, even if the file already exists.
For backwards compatibility with 1.0.x, this option can be given as
last argument, too.
.TP
.B \-\-no\-overwrite
Never overwrite an existing file, even if the old certificate's key length
is too small or if it uses an obsoltete signature algorithm.
.TP
.B \-\-expiration\-days \fIN\fR
Make the new certificate expire in \fIN\fR days.
Default is 3650.
.SH "SEE ALSO"
.IR "openssl" (1)
.SH AUTHOR
The program author is Thom May <thom@debian.org>, manual
page was written for completeness by Fabio M. Di Nitto
<fabbione@fabbione.net>, for the Debian GNU/Linux system
(but may be used by others).
